# Generated by Django 4.1.7 on 2023-04-05 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0002_personnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "Mac - Run MacOS"),
                    (
                        "Serveur",
                        "Serveur -             Simple Server to deploy virtual machines",
                    ),
                    ("Switch", "Switch -             To maintains and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 5, 8, 34, 50, 726349)
            ),
        ),
    ]
