# Generated by Django 4.1.7 on 2023-04-05 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0003_machine_mach_machine_maintenancedate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Personnel",
            new_name="Personne",
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 5, 10, 1, 48, 597771)
            ),
        ),
    ]
