# Generated by Django 4.1.7 on 2023-04-24 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0004_rename_personnel_personne_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 4, 24, 7, 30, 51, 620283)
            ),
        ),
    ]
