# Generated by Django 4.1.7 on 2023-05-11 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0007_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 11, 6, 24, 17, 241208)
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personne",
            name="nom",
            field=models.CharField(max_length=20),
        ),
    ]
