# Generated by Django 4.1.7 on 2023-05-11 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0009_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "MAc - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 11, 7, 39, 32, 910372)
            ),
        ),
    ]
