# Generated by Django 4.1.7 on 2023-05-18 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0022_personne_prenom_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="personne",
            name="secteur",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 18, 10, 34, 56, 492316)
            ),
        ),
    ]
