# Generated by Django 4.1.7 on 2023-05-19 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0031_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupe",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 10, 2, 31, 686736)
            ),
        ),
    ]
