# Generated by Django 4.1.7 on 2023-05-19 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0033_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="machine",
            name="ip",
            field=models.GenericIPAddressField(default="0.0.0.0"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 12, 30, 48, 772771)
            ),
        ),
    ]
