# Generated by Django 4.1.7 on 2023-05-19 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0040_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="ip",
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 13, 19, 32, 239596)
            ),
        ),
    ]
