# Generated by Django 4.1.7 on 2023-05-22 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0043_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="email",
            field=models.EmailField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machine",
            name="etat",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 8, 39, 42, 89999)
            ),
        ),
    ]
