# Generated by Django 4.1.7 on 2023-05-22 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0044_machine_email_machine_etat_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Logout",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="email",
        ),
        migrations.AddField(
            model_name="personne",
            name="email",
            field=models.EmailField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 8, 55, 7, 14375)
            ),
        ),
    ]
