# Generated by Django 4.1.7 on 2023-05-22 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "computerApp",
            "0045_delete_logout_remove_machine_email_personne_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 9, 27, 28, 70435)
            ),
        ),
        migrations.AlterField(
            model_name="personne",
            name="sexe",
            field=models.CharField(
                choices=[("M", "Employer Masculin"), ("F", "Employer Féminin")],
                default="M",
                max_length=2,
            ),
        ),
    ]
