# Generated by Django 4.1.7 on 2023-05-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0046_alter_machine_maintenancedate_alter_personne_sexe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 9, 34, 10, 195451)
            ),
        ),
        migrations.AlterField(
            model_name="personne",
            name="secteur",
            field=models.CharField(
                choices=[
                    ("DG", "Direction Générala"),
                    ("RH", "Ressource Humaine"),
                    ("DST", "Direction des services techniques"),
                    ("DF", "Direction financière"),
                    ("DSI", "Direction des services informatiques"),
                    ("DF", "Direction Marketing"),
                    ("DF", "Direction Marketing"),
                    ("ND", "Non défini"),
                ],
                default="ND",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="personne",
            name="sexe",
            field=models.CharField(
                choices=[
                    ("M", "Employer Masculin"),
                    ("F", "Employer Féminin"),
                    ("ND", "Non Défini"),
                ],
                default="ND",
                max_length=50,
            ),
        ),
    ]
