# Generated by Django 4.1.7 on 2023-05-22 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "computerApp",
            "0047_alter_machine_maintenancedate_alter_personne_secteur_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 11, 10, 17, 754324)
            ),
        ),
        migrations.AlterField(
            model_name="personne",
            name="secteur",
            field=models.CharField(
                choices=[
                    ("DG", "Direction Générale"),
                    ("RH", "Ressource Humaine"),
                    ("DST", "Direction des services techniques"),
                    ("DF", "Direction Financière"),
                    ("DSI", "Direction des services informatiques"),
                    ("DM", "Direction Marketing"),
                    ("ND", "Non défini"),
                ],
                default="ND",
                max_length=50,
            ),
        ),
    ]
