# Generated by Django 4.1.7 on 2023-05-22 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0048_alter_machine_maintenancedate_alter_personne_secteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 22, 11, 13, 35, 195363)
            ),
        ),
    ]
